context:
  name: cargo-shear
  version: "1.7.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Boshen/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f8ef7bb5a02389ce72c1412d03a7e411d56d26bfdbd8bd343a670b630e1395b9

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: cargo-shear --help

about:
  homepage: https://github.com/boshen/cargo-shear
  summary: Detect and remove unused dependencies from Cargo.toml.
  description: |
    Detect and fix unused/misplaced dependencies from Cargo.toml in Rust projects.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://docs.rs/example-package
  repository: https://github.com/boshen/cargo-shear

extra:
  recipe-maintainers:
    - Hofer-Julian
